apiVersion: apps/v1  #changed this from extensions/v1beta1
kind: Deployment     #check the deploy folder to see the original yaml file
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1   #this was the source of the error
  selector:     #added this selector to match the spec.template.metadata.label
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy  #selector matches label
    spec:
      containers:
      - image: chimezdev/simple-reverse-proxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always

